# -*- coding: utf-8 -*-
"""Dashboard de ventas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148WSWobBTIaycT_7KMtOxSQN2HCoIAVp

#Dashboard de metricas de ventas
"""

#librerias principales
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import seaborn as sns
!pip install streamlit
import streamlit as st

#creamos datos sintéticos realistas

np.random.seed(42)

fechas=pd.date_range('2023-01-01', '2024-12-31',freq='D')
n_productos=['Laptop','Mouse','Teclado','Monitor','Auriculares']
regiones=['Norte','Sur','Este','Oeste','Centro']

#Generar el Dataset con el que vamos a trabajar

data=[]
for fecha in fechas:
  for x in range(np.random.poisson(10)): #10 ventas promedio por día
    data.append({
        'Fecha':fecha,
        'Producto':np.random.choice(n_productos),
        'region':np.random.choice(regiones),
        'cantidad':np.random.randint(1,6),
        'precio_unitario':np.random.uniform(50,1500),
        'vendedor':f'Vendedor{np.random.randint(1,21)}'
    })

#Ahora cargamos nuestros datos sinteticos a un dataframe
df=pd.DataFrame(data)
df['ventas_totales']=df['cantidad']*df['precio_unitario']
df.info()

#Generamos un pequeño reporte de nuestros dataframe

print("Shape del dataset:",df.shape)
print("Primeras filas: ")
print(df.head())
print("Información general:" )
print(df.info())
print("Descripción estadística: ")
print(df.describe())

#Visualizaciones con plotly
#Visualización por mes

df_mensual=df.groupby(df['Fecha'].dt.to_period('M'))['ventas_totales'].sum().reset_index()
df_mensual['Fecha']=df_mensual['Fecha'].astype(str)
df_mensual

#Grafico mensual

fig_mensual=px.line(df_mensual,x='Fecha',y='ventas_totales',title='Tendencia de Ventas mensuales',
                    labels={'venta_totales':'Ventas ($)','Fecha':'Mes'})

fig_mensual.update_traces(line=dict(color='#FF5733',width=2))
fig_mensual.show()

#2. Top productos
df_productos= df.groupby('Producto')['ventas_totales'].sum().sort_values(ascending=False)
fig_productos=px.bar(x=df_productos.values,y=df_productos.index, orientation='h',title='Ventas por Producto',labels={'x':'Ventas Totales','y':'Producto'})
fig_productos.update_traces(marker_color='#FF5733')
fig_productos.show()

#3. Análisis geografico

df_regiones=df.groupby('region')['ventas_totales'].sum().reset_index()
fig_regiones=px.pie(df_regiones,values='ventas_totales',names='region',title='Distribución de Ventas por Región',
                    color_discrete_sequence=px.colors.sequential.RdBu)
fig_regiones.show()

#4. Correlación entre variables
df_corr=df[['cantidad','precio_unitario','ventas_totales']].corr()
fig_heatmap=px.imshow(df_corr,text_auto=True,aspect="auto",title='Correlación entre variables numéricas',
                      color_continuous_scale='Viridis')
fig_heatmap.show()

#5. Distribución de ventas

fig_dist=px.histogram(df,x='ventas_totales',nbins=50,title='Distribución de ventas individuales')
fig_dist.update_layout(bargap=0.2)
fig_dist.update_traces(marker_color='#FF5733') # Añadir color a las barras
fig_dist.show()

#Configuración de la página

st.set_page_config(page_title="Dashboard de ventas",page_icon=":bar_chart:",layout="wide")

st.title("📶 Dashboard de ventas")
st.markdown("---")

st.sidebar.header("Filtros")
productos_seleccionados=st.sidebar.multiselect(
    "Selecciona productos",
    options=df['Producto'].unique(),
    default=df['Producto'].unique()
    )

regiones_seleccionadas=st.sidebar.multiselect(
    "Selecciona regiones",
    options=df['region'].unique(),
    default=df['region'].unique()
)

#Filtrar datos basados en seleccion
df_filtrado=df[(df['Producto'].isin(productos_seleccionados)) &
               (df['region'].isin(regiones_seleccionadas))]

#Métricas principales

col1,col2,col3, col4=st.columns(4)
with col1:
  st.metric("Ventas Totales",f"${df_filtrado['ventas_totales'].sum():,.0f}")
with col2:
  st.metric("Promedio por Venta",f"${df_filtrado['ventas_totales'].mean():,.0f}")
with col3:
  st.metric("Número de ventas",f"{len(df_filtrado):,}")
with col4:
  crecimiento=((df_filtrado[df_filtrado['Fecha']>='2024-01-01']['ventas_totales'].sum()/
                            df_filtrado[df_filtrado['Fecha']<'2024-01-01']['ventas_totales'].sum())-1)*100
  st.metric("Crecimiento 2024",f"{crecimiento:.1f}%")

#layout con dos columnas

col1, col2=st.columns((2))
with col1:
  st.plotly_chart(fig_mensual,use_container_width=True)
  st.plotly_chart(fig_productos,use_container_width=True)
with col2:
  st.plotly_chart(fig_regiones,use_container_width=True)
  st.plotly_chart(fig_heatmap,use_container_width=True)

#Gráfico completo en la parte superior

st.plotly_chart(fig_dist,use_container_width=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dashboard_ventas.py
# #librerias principales
# import pandas as pd
# import plotly.express as px
# import plotly.graph_objects as go
# from plotly.subplots import make_subplots
# import numpy as np
# import matplotlib.pyplot as plt
# from datetime import datetime, timedelta
# import seaborn as sns
# import streamlit as st
# 
# #creamos datos sintéticos realistas
# np.random.seed(42)
# fechas=pd.date_range('2023-01-01', '2024-12-31',freq='D')
# n_productos=['Laptop','Mouse','Teclado','Monitor','Auriculares']
# regiones=['Norte','Sur','Este','Oeste','Centro']
# 
# #Generar el Dataset con el que vamos a trabajar
# data=[]
# for fecha in fechas:
#   for x in range(np.random.poisson(10)): #10 ventas promedio por día
#     data.append({
#         'Fecha':fecha,
#         'Producto':np.random.choice(n_productos),
#         'region':np.random.choice(regiones),
#         'cantidad':np.random.randint(1,6),
#         'precio_unitario':np.random.uniform(50,1500),
#         'vendedor':f'Vendedor{np.random.randint(1,21)}'
#     })
# 
# #Ahora cargamos nuestros datos sinteticos a un dataframe
# df=pd.DataFrame(data)
# df['ventas_totales']=df['cantidad']*df['precio_unitario']
# 
# #Visualizaciones con plotly
# #Visualización por mes
# df_mensual=df.groupby(df['Fecha'].dt.to_period('M'))['ventas_totales'].sum().reset_index()
# df_mensual['Fecha']=df_mensual['Fecha'].astype(str)
# 
# #Grafico mensual
# fig_mensual=px.line(df_mensual,x='Fecha',y='ventas_totales',title='Tendencia de Ventas mensuales',
#                     labels={'venta_totales':'Ventas ($)','Fecha':'Mes'})
# fig_mensual.update_traces(line=dict(color='#FF5733',width=2))
# 
# #2. Top productos
# df_productos= df.groupby('Producto')['ventas_totales'].sum().sort_values(ascending=False)
# fig_productos=px.bar(x=df_productos.values,y=df_productos.index, orientation='h',title='Ventas por Producto',labels={'x':'Ventas Totales','y':'Producto'})
# fig_productos.update_traces(marker_color='#FF5733')
# 
# #3. Análisis geografico
# df_regiones=df.groupby('region')['ventas_totales'].sum().reset_index()
# fig_regiones=px.pie(df_regiones,values='ventas_totales',names='region',title='Distribución de Ventas por Región',
#                     color_discrete_sequence=px.colors.sequential.RdBu)
# 
# #4. Correlación entre variables
# df_corr=df[['cantidad','precio_unitario','ventas_totales']].corr()
# fig_heatmap=px.imshow(df_corr,text_auto=True,aspect="auto",title='Correlación entre variables numéricas',
#                       color_continuous_scale='Viridis')
# 
# #5. Distribución de ventas
# fig_dist=px.histogram(df,x='ventas_totales',nbins=50,title='Distribución de ventas individuales')
# fig_dist.update_layout(bargap=0.2)
# fig_dist.update_traces(marker_color='#FF5733') # Añadir color a las barras
# 
# 
# #Configuración de la página
# st.set_page_config(page_title="Dashboard de ventas",page_icon=":bar_chart:",layout="wide")
# st.title("📶 Dashboard de ventas")
# st.markdown("---")
# 
# st.sidebar.header("Filtros")
# productos_seleccionados=st.sidebar.multiselect(
#     "Selecciona productos",
#     options=df['Producto'].unique(),
#     default=df['Producto'].unique()
#     )
# 
# regiones_seleccionadas=st.sidebar.multiselect(
#     "Selecciona regiones",
#     options=df['region'].unique(),
#     default=df['region'].unique()
# )
# 
# #Filtrar datos basados en seleccion
# df_filtrado=df[(df['Producto'].isin(productos_seleccionados)) &
#                (df['region'].isin(regiones_seleccionadas))]
# 
# #Métricas principales
# col1,col2,col3, col4=st.columns(4)
# with col1:
#   st.metric("Ventas Totales",f"${df_filtrado['ventas_totales'].sum():,.0f}")
# with col2:
#   st.metric("Promedio por Venta",f"${df_filtrado['ventas_totales'].mean():,.0f}")
# with col3:
#   st.metric("Número de ventas",f"{len(df_filtrado):,}")
# with col4:
#   crecimiento=((df_filtrado[df_filtrado['Fecha']>='2024-01-01']['ventas_totales'].sum()/
#                             df_filtrado[df_filtrado['Fecha']<'2024-01-01']['ventas_totales'].sum())-1)*100
#   st.metric("Crecimiento 2024",f"{crecimiento:.1f}%")
# 
# #layout con dos columnas
# col1, col2=st.columns((2))
# with col1:
#   st.plotly_chart(fig_mensual,use_container_width=True)
#   st.plotly_chart(fig_productos,use_container_width=True)
# with col2:
#   st.plotly_chart(fig_regiones,use_container_width=True)
#   st.plotly_chart(fig_heatmap,use_container_width=True)
# 
# #Gráfico completo en la parte superior
# st.plotly_chart(fig_dist,use_container_width=True)
#

!streamlit run dashboard_ventas.py & npx localtunnel --port 8501

